package POJOS;
// Generated 8 abr. 2024 16:20:08 by Hibernate Tools 4.3.1



/**
 * RelContribuyenteOrdenanza generated by hbm2java
 */
public class RelContribuyenteOrdenanza  implements java.io.Serializable {


     private int id;
     private Contribuyente contribuyente;
     private Ordenanza ordenanza;

    public RelContribuyenteOrdenanza() {
    }

	
    public RelContribuyenteOrdenanza(int id) {
        this.id = id;
    }
    public RelContribuyenteOrdenanza(int id, Contribuyente contribuyente, Ordenanza ordenanza) {
       this.id = id;
       this.contribuyente = contribuyente;
       this.ordenanza = ordenanza;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public Ordenanza getOrdenanza() {
        return this.ordenanza;
    }
    
    public void setOrdenanza(Ordenanza ordenanza) {
        this.ordenanza = ordenanza;
    }




}


